### ISSUE TITLE
Where is it though

### ISSUE THREAD

**Issue by logaretm** [baianat/blexar#1]
> "An HTML, CSS and JavaScript framework for developing responsive modern web interfaces, focused on usability and minimal sizes, with all the needed / necessary extensions." 

PogU :open_mouth: 

Where is it though? :man_shrugging:

**Comment by AsamyX** [comment]
https://i.ytimg.com/vi/2xhEfMNCPGs/hqdefault.jpg

**Comment by Abdelrahman3D** [comment]
We are working on a great framework. We are keeping it private for now, due to marketing reasons, in order to achieve more suspense and attraction you know. So please stay tuned, we are coming soon! 🤙🤙
